export const media = {
  images: {
    houseHero: '/media/oriel/01_A_CASA_Hero.jpg',
    houseLifestyle: '/media/oriel/02_A_CASA_Interior_Lifestyle.jpg',
    atelierMaster: '/media/oriel/03_ATELIER_Master_Tailor.jpg',
    atelierDetail: '/media/oriel/04_ATELIER_Tailoring_Detail.jpg',
    womenClassic: '/media/oriel/05_MULHERES_Campaign_Classic_Corridor.jpg',
    womenModern: '/media/oriel/06_MULHERES_Campaign_Modern_Camel_Coat.jpg',
    burgundyDress: '/media/oriel/07_MULHERES_Burgundy_Silk_Dress_Front.jpg',
    burgundyDressAlt: '/media/oriel/08_MULHERES_Burgundy_Silk_Dress_Second_View.jpg',
    navyCoat: '/media/oriel/09_MULHERES_Navy_Coat_Full.jpg',
    navyCoatAlt: '/media/oriel/10_MULHERES_Navy_Coat_Second_View.jpg',
    ivoryBlouse: '/media/oriel/11_MULHERES_Cream_Drape_Blouse_Full.jpg',
    ivoryBlouseAlt: '/media/oriel/12_MULHERES_Cream_Drape_Blouse_Second_View.jpg',
    menEstate: '/media/oriel/13_HOMENS_Campaign_Estate_Walk.jpg',
    menModern: '/media/oriel/14_HOMENS_Campaign_Modern_Grey_Coat.jpg',
    greenPolo: '/media/oriel/15_HOMENS_Green_Polo_Full.jpg',
    greenPoloAlt: '/media/oriel/16_HOMENS_Green_Polo_Second_View.jpg',
    charcoalTrouser: '/media/oriel/17_HOMENS_Blue_Shirt_Full.jpg',
    charcoalTrouserAlt: '/media/oriel/18_HOMENS_Blue_Shirt_Second_View.jpg',
    leatherEditorial: '/media/oriel/19_LEATHER_GOODS_Mens_Bag_Editorial.jpg',
    objectsStill: '/media/oriel/20_LEATHER_GOODS_Bag_Still_Life.jpg',
    structuredBag: '/media/oriel/21_LEATHER_GOODS_Bag_On_Pedestal.jpg',
    structuredBagAlt: '/media/oriel/22_LEATHER_GOODS_Womens_Bag_Carry_Full.jpg',
    structuredBagAlt2: '/media/oriel/23_LEATHER_GOODS_Womens_Bag_Carry_Alt.jpg',
    loafers: '/media/oriel/24_ACCESSORIES_Loafers_Still_Life.jpg',
    loafersAlt: '/media/oriel/25_ACCESSORIES_Loafers_On_Foot.jpg',
    scarf: '/media/oriel/26_ACCESSORIES_Silk_Scarf_Still_Life.jpg',
    scarfAlt: '/media/oriel/27_ACCESSORIES_Silk_Scarf_On_Model.jpg',
    escape: '/media/oriel/28_CAMPAIGN_Travel_Coastline.jpg',
    campaignDuo: '/media/oriel/29_CAMPAIGN_Duo_Palace.jpg',
  },
  videos: {
    intro: '/video/oriel/intro.mp4',
    house: '/video/oriel/a-casa.mp4',
    atelier: '/video/oriel/atelier.mp4',
    women: '/video/oriel/women.mp4',
    men: '/video/oriel/men.mp4',
    leather: '/video/oriel/leather-goods.mp4',
    scarf: '/video/oriel/accessories-scarf.mp4',
    duo: '/video/oriel/campaign-duo.mp4',
  },
} as const;
