import { MediaPlaceholder } from './MediaPlaceholder'; import styles from './maison.module.css';
export function MaisonExperience(){return <main className={styles.page}>
 <section className={styles.hero}><MediaPlaceholder label="Archive film · 1994 / now" tone="stone" video/><div className={styles.shade}/><div><span>THE MAISON · SINCE 1994</span><h1>One atelier,<br/><em>one standard.</em></h1></div></section>
 <section className={styles.numbers}><div><strong>1994</strong><span>Founded, 9e arrondissement</span></div><div><strong>09</strong><span>Pairs of hands per coat</span></div><div><strong>04</strong><span>Named mills, all European</span></div><div><strong>∞</strong><span>Alterations, for life</span></div></section>
 <section className={styles.savoir}><div className={styles.title}><span>SAVOIR-FAIRE</span><h2>Eleven days,<br/>nine stages.</h2></div>{[
  ['I','Pattern drawn in kraft paper','Every style is redrawn each season rather than scaled from an archive block.'],['II','Cloth rested before cutting','Time releases the tension from the mill before a blade touches it.'],['III','Cut with a table knife','A clean line, cut once, marked by hand.'],['IV','Canvas basted into the chest','Two days of work that decide how the shoulder falls for the life of the coat.'],['V','First fitting on the body','Never on a stand. What fails the fitting goes back to stage one.'],['VI — IX','Buttonholes, lining, press, inspection','The final four stages happen slowly enough to notice what changed.']
 ].map(([n,t,d],i)=><article key={n}><div className={styles.stageMedia}><MediaPlaceholder label={`Stage ${n} · ${t}`} tone={i%3===0?'warm':i%3===1?'ink':'stone'}/></div><div className={styles.stageText}><span>{n}</span><h3>{t}</h3><p>{d}</p><small>BY HAND</small></div></article>)}</section>
 <section className={styles.mills}><div><span>THE MILLS</span><h2>Where the cloth<br/><em>comes from.</em></h2></div><div>{[['Ferrand, Roubaix','Double wool · since 1908'],['Belmonte, Biella','Cashmere · since 1931'],['Vandael, Kortrijk','Waxed linen · since 1954'],['Cordal, Ubrique','Calf leather · since 1967']].map(([a,b],i)=><div key={a}><b>0{i+1}</b><h3>{a}</h3><span>{b}</span></div>)}</div></section>
 <section className={styles.repair}><div className={styles.repairMedia}><MediaPlaceholder label="Repair atelier · film" tone="ink" video/></div><div><span>CARE & REPAIR</span><h2>A garment returns<br/><em>as often as it needs to.</em></h2><ul><li>Alterations, first and forever <b>Included</b></li><li>Repair, quoted at cost <b>By request</b></li><li>Seasonal press and store <b>On request</b></li></ul><button>Book a repair →</button></div></section>
 </main>}
